require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VclipsController do

  # This should return the minimal set of attributes required to create a valid
  # Vclip. As you add validations to Vclip, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "vstruct_id" => "10f92205-25a8-4590-94a9-6ccfa0590545" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VclipsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all vclips as @vclips" do
      vclip = Vclip.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vclips).should eq([vclip])
    end
  end

  describe "GET show" do
    it "assigns the requested vclip as @vclip" do
      vclip = Vclip.create! valid_attributes
      get :show, {:id => vclip.to_param}, valid_session
      assigns(:vclip).should eq(vclip)
    end
  end

  describe "GET new" do
    it "assigns a new vclip as @vclip" do
      get :new, {}, valid_session
      assigns(:vclip).should be_a_new(Vclip)
    end
  end

  describe "GET edit" do
    it "assigns the requested vclip as @vclip" do
      vclip = Vclip.create! valid_attributes
      get :edit, {:id => vclip.to_param}, valid_session
      assigns(:vclip).should eq(vclip)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Vclip" do
        expect {
          post :create, {:vclip => valid_attributes}, valid_session
        }.to change(Vclip, :count).by(1)
      end

      it "assigns a newly created vclip as @vclip" do
        post :create, {:vclip => valid_attributes}, valid_session
        assigns(:vclip).should be_a(Vclip)
        assigns(:vclip).should be_persisted
      end

      it "redirects to the created vclip" do
        post :create, {:vclip => valid_attributes}, valid_session
        response.should redirect_to(Vclip.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vclip as @vclip" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vclip.any_instance.stub(:save).and_return(false)
        post :create, {:vclip => { "vstruct_id" => "invalid value" }}, valid_session
        assigns(:vclip).should be_a_new(Vclip)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vclip.any_instance.stub(:save).and_return(false)
        post :create, {:vclip => { "vstruct_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vclip" do
        vclip = Vclip.create! valid_attributes
        # Assuming there are no other vclips in the database, this
        # specifies that the Vclip created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Vclip.any_instance.should_receive(:update).with({ "vstruct_id" => "" })
        put :update, {:id => vclip.to_param, :vclip => { "vstruct_id" => "" }}, valid_session
      end

      it "assigns the requested vclip as @vclip" do
        vclip = Vclip.create! valid_attributes
        put :update, {:id => vclip.to_param, :vclip => valid_attributes}, valid_session
        assigns(:vclip).should eq(vclip)
      end

      it "redirects to the vclip" do
        vclip = Vclip.create! valid_attributes
        put :update, {:id => vclip.to_param, :vclip => valid_attributes}, valid_session
        response.should redirect_to(vclip)
      end
    end

    describe "with invalid params" do
      it "assigns the vclip as @vclip" do
        vclip = Vclip.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vclip.any_instance.stub(:save).and_return(false)
        put :update, {:id => vclip.to_param, :vclip => { "vstruct_id" => "invalid value" }}, valid_session
        assigns(:vclip).should eq(vclip)
      end

      it "re-renders the 'edit' template" do
        vclip = Vclip.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vclip.any_instance.stub(:save).and_return(false)
        put :update, {:id => vclip.to_param, :vclip => { "vstruct_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vclip" do
      vclip = Vclip.create! valid_attributes
      expect {
        delete :destroy, {:id => vclip.to_param}, valid_session
      }.to change(Vclip, :count).by(-1)
    end

    it "redirects to the vclips list" do
      vclip = Vclip.create! valid_attributes
      delete :destroy, {:id => vclip.to_param}, valid_session
      response.should redirect_to(vclips_url)
    end
  end

end
