require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VstructsController do

  # This should return the minimal set of attributes required to create a valid
  # Vstruct. As you add validations to Vstruct, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "label" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VstructsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all vstructs as @vstructs" do
      vstruct = Vstruct.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vstructs).should eq([vstruct])
    end
  end

  describe "GET show" do
    it "assigns the requested vstruct as @vstruct" do
      vstruct = Vstruct.create! valid_attributes
      get :show, {:id => vstruct.to_param}, valid_session
      assigns(:vstruct).should eq(vstruct)
    end
  end

  describe "GET new" do
    it "assigns a new vstruct as @vstruct" do
      get :new, {}, valid_session
      assigns(:vstruct).should be_a_new(Vstruct)
    end
  end

  describe "GET edit" do
    it "assigns the requested vstruct as @vstruct" do
      vstruct = Vstruct.create! valid_attributes
      get :edit, {:id => vstruct.to_param}, valid_session
      assigns(:vstruct).should eq(vstruct)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Vstruct" do
        expect {
          post :create, {:vstruct => valid_attributes}, valid_session
        }.to change(Vstruct, :count).by(1)
      end

      it "assigns a newly created vstruct as @vstruct" do
        post :create, {:vstruct => valid_attributes}, valid_session
        assigns(:vstruct).should be_a(Vstruct)
        assigns(:vstruct).should be_persisted
      end

      it "redirects to the created vstruct" do
        post :create, {:vstruct => valid_attributes}, valid_session
        response.should redirect_to(Vstruct.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vstruct as @vstruct" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vstruct.any_instance.stub(:save).and_return(false)
        post :create, {:vstruct => { "label" => "invalid value" }}, valid_session
        assigns(:vstruct).should be_a_new(Vstruct)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vstruct.any_instance.stub(:save).and_return(false)
        post :create, {:vstruct => { "label" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vstruct" do
        vstruct = Vstruct.create! valid_attributes
        # Assuming there are no other vstructs in the database, this
        # specifies that the Vstruct created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Vstruct.any_instance.should_receive(:update).with({ "label" => "MyString" })
        put :update, {:id => vstruct.to_param, :vstruct => { "label" => "MyString" }}, valid_session
      end

      it "assigns the requested vstruct as @vstruct" do
        vstruct = Vstruct.create! valid_attributes
        put :update, {:id => vstruct.to_param, :vstruct => valid_attributes}, valid_session
        assigns(:vstruct).should eq(vstruct)
      end

      it "redirects to the vstruct" do
        vstruct = Vstruct.create! valid_attributes
        put :update, {:id => vstruct.to_param, :vstruct => valid_attributes}, valid_session
        response.should redirect_to(vstruct)
      end
    end

    describe "with invalid params" do
      it "assigns the vstruct as @vstruct" do
        vstruct = Vstruct.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vstruct.any_instance.stub(:save).and_return(false)
        put :update, {:id => vstruct.to_param, :vstruct => { "label" => "invalid value" }}, valid_session
        assigns(:vstruct).should eq(vstruct)
      end

      it "re-renders the 'edit' template" do
        vstruct = Vstruct.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vstruct.any_instance.stub(:save).and_return(false)
        put :update, {:id => vstruct.to_param, :vstruct => { "label" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vstruct" do
      vstruct = Vstruct.create! valid_attributes
      expect {
        delete :destroy, {:id => vstruct.to_param}, valid_session
      }.to change(Vstruct, :count).by(-1)
    end

    it "redirects to the vstructs list" do
      vstruct = Vstruct.create! valid_attributes
      delete :destroy, {:id => vstruct.to_param}, valid_session
      response.should redirect_to(vstructs_url)
    end
  end

end
